In [ ]:
import pandas as pd
import numpy as np
import os

print("Starting up the Air Quality data compiler...")

file_map = {
    "India": "/content/IndiaPM25-V6GL0203-Annual-REGIONAL-1998-2023-wThresFrac.csv",
    "Canada": "/content/CanadaPM25-V6GL0203-Annual-REGIONAL-1998-2023-wThresFrac.csv",
    "China": "/content/ChinaPM25-V6GL0203-Annual-REGIONAL-1998-2023-wThresFrac.csv",
    "USA": "/content/UnitedStatesPM25-V6GL0203-Annual-REGIONAL-1998-2023-wThresFrac.csv",
    "Global": "/content/GlobalPM25-V6GL0203-Annual-1998-2023-wThresFrac.csv"
}

all_dfs = []
print("Loading datasets from around the world...")

for country, filename in file_map.items():
    if os.path.exists(filename):
        temp_df = pd.read_csv(filename)
        temp_df['Source'] = country
        all_dfs.append(temp_df)
        print(f"  ✓ Successfully loaded {country} data.")
    else:
        print(f"Couldn't find the file for {country} at {filename}.")

if not all_dfs:
    print("\nError: No data found. Please make sure your CSV files are uploaded to Colab!")
else:
    master_df = pd.concat(all_dfs, ignore_index=True)

    target_col = 'Population-Weighted PM2.5 [ug/m3]'

    master_df = master_df.sort_values(by=['Source', 'Region', 'Year']).reset_index(drop=True)

    master_df['pm_lag_1'] = master_df.groupby(['Source', 'Region'])[target_col].shift(1)

    master_df['pm_lag_2'] = master_df.groupby(['Source', 'Region'])[target_col].shift(2)

    master_df['pm_lag_3'] = master_df.groupby(['Source', 'Region'])[target_col].shift(3)

    master_df['pm_roll_3'] = master_df[['pm_lag_1', 'pm_lag_2', 'pm_lag_3']].mean(axis=1)

    columns_to_keep = [
        'Source',
        'Year',
        'Region',
        'Geographic-Mean PM2.5 [ug/m3]',
        'Population Coverage [%]',
        'Geographic Coverage [%]',
        'pm_lag_1',
        'pm_lag_2',
        'pm_lag_3',
        'pm_roll_3',
        target_col
    ]

    ts_df = master_df[columns_to_keep].copy()

    ts_df = ts_df.dropna().reset_index(drop=True)

    ts_df = ts_df.rename(columns={target_col: 'Target_PM25_Current_Year'})

    print("\n Data transformation complete! Here is a sneak peek at your new Time Series dataset:")
    display(ts_df.head(10))

Starting up the Air Quality data compiler...
Loading datasets from around the world...
  ✓ Successfully loaded India data.
  ✓ Successfully loaded Canada data.
  ✓ Successfully loaded China data.
  ✓ Successfully loaded USA data.
  ✓ Successfully loaded Global data.

 Data transformation complete! Here is a sneak peek at your new Time Series dataset:

,Source,Year,Region,Geographic-Mean PM2.5 [ug/m3],Population Coverage [%],Geographic Coverage [%],pm_lag_1,pm_lag_2,pm_lag_3,pm_roll_3,Target_PM25_Current_Year
0,Canada,2001,Alberta,4.5,100.0,100.0,7.2,6.9,9.3,7.800000,6.7
1,Canada,2002,Alberta,5.6,100.0,100.0,6.7,7.2,6.9,6.933333,7.0
2,Canada,2003,Alberta,5.5,100.0,100.0,7.0,6.7,7.2,6.966667,8.0
3,Canada,2004,Alberta,5.5,100.0,100.0,8.0,7.0,6.7,7.233333,6.9
4,Canada,2005,Alberta,4.7,100.0,100.0,6.9,8.0,7.0,7.300000,6.7
5,Canada,2006,Alberta,5.3,100.0,100.0,6.7,6.9,8.0,7.200000,7.2
6,Canada,2007,Alberta,5.1,100.0,100.0,7.2,6.7,6.9,6.933333,7.0
7,Canada,2008,Alberta,5.3,100.0,100.0,7.0,7.2,6.7,6.966667,7.1
8,Canada,2009,Alberta,5.3,100.0,100.0,7.1,7.0,7.2,7.100000,7.6
9,Canada,2010,Alberta,6.0,100.0,100.0,7.6,7.1,7.0,7.233333,8.4

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import os

print(" Step 1: Prepping the data for training...")

features = [
    'Year',
    'Geographic-Mean PM2.5 [ug/m3]',
    'Population Coverage [%]',
    'Geographic Coverage [%]',
    'pm_lag_1',
    'pm_lag_2',
    'pm_lag_3',
    'pm_roll_3'
]
target = 'Target_PM25_Current_Year'

X = ts_df[features]
y = ts_df[target]

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

print("\n Step 2: Training the Random Forest model. Stand by...")

model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

y_val_pred = model.predict(X_val)

r2 = r2_score(y_val, y_val_pred)
mae = mean_absolute_error(y_val, y_val_pred)

print(f"   Accuracy (R² Score): {r2 * 100:.2f}%")
print(f"   Margin of Error (MAE): It's usually off by about {mae:.2f} ug/m3")

test_file_path = '/content/Test_Features.csv'

print("\n Step 3: Processing the official Test Dataset...")
if os.path.exists(test_file_path):
    test_df = pd.read_csv(test_file_path)

    test_df = test_df.rename(columns={
        'pm_lag1': 'pm_lag_1',
        'pm_lag2': 'pm_lag_2',
        'pm_lag3': 'pm_lag_3',
        'pm_roll3': 'pm_roll_3'
    })

    missing_cols = [col for col in features if col not in test_df.columns]

    if missing_cols:
        print(f" The test dataset is missing some expected columns: {missing_cols}")
    else:
        X_test_final = test_df[features]

        final_predictions = model.predict(X_test_final)

        test_df['Predicted_PM25'] = final_predictions

        print("  ✓ Predictions successfully generated!")
        print("\nHere's a sneak peek at the first 5 predictions:")
        display(test_df[['Year', 'Region', 'Predicted_PM25']].head())

        output_filename = '/content/Final_Test_Predictions.csv'
        test_df.to_csv(output_filename, index=False)
        print(f"\n  Saved your predictions to: {output_filename}")

else:
    print(f" Couldn't find {test_file_path}. Did you upload it to your Colab environment?")

 Step 1: Prepping the data for training...

 Step 2: Training the Random Forest model. Stand by...
   Accuracy (R² Score): 98.29%
   Margin of Error (MAE): It's usually off by about 1.21 ug/m3

 Step 3: Processing the official Test Dataset...
  ✓ Predictions successfully generated!

Here's a sneak peek at the first 5 predictions:

   Year                 Region  Predicted_PM25
0  2021            Afghanistan          34.954
1  2022            Afghanistan          34.984
2  2023            Afghanistan          38.511
3  2024            Afghanistan          37.432
4  2021  Akrotiri and Dhekelia          13.627

  Saved your predictions to: /content/Final_Test_Predictions.csv

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
import os

print("Starting up the Air Quality predictor...")

print("Training the model on historical data. This might take a second...")

features = [
    'Year',
    'Geographic-Mean PM2.5 [ug/m3]',
    'Population Coverage [%]',
    'Geographic Coverage [%]',
    'pm_lag_1',
    'pm_lag_2',
    'pm_lag_3',
    'pm_roll_3'
]
target = 'Target_PM25_Current_Year'

model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(ts_df[features], ts_df[target])


def categorize_pm25(val):
    if val <= 12.0:
        return 'Good'
    elif val <= 35.4:
        return 'Moderate'
    elif val <= 55.4:
        return 'Sensitive'
    else:
        return 'Critical'


test_file_path = '/content/Test_Features.csv'

if os.path.exists(test_file_path):
    print(f" Found the test file at {test_file_path}. Processing now...")

    test_df = pd.read_csv(test_file_path)

    test_df = test_df.rename(columns={
        'pm_lag1': 'pm_lag_1',
        'pm_lag2': 'pm_lag_2',
        'pm_lag3': 'pm_lag_3',
        'pm_roll3': 'pm_roll_3'
    })

    X_test_final = test_df[features]

    raw_predictions = model.predict(X_test_final)

    class_predictions = [categorize_pm25(val) for val in raw_predictions]

    final_output = pd.DataFrame({
        'Year': test_df['Year'],
        'Region': test_df['Region'],
        'Predicted_Air_Quality': class_predictions
    })

    print("\n Here's a look at the predictions:")

    pd.set_option('display.max_rows', None)
    display(final_output)
    pd.reset_option('display.max_rows')

    save_path = '/content/Final_Classified_Predictions.csv'
    final_output.to_csv(save_path, index=False)
    print(f"\n Success! Your classified predictions are saved to: {save_path}")

else:

    print(f"I couldn't find {test_file_path}. Did you forget to upload it to Colab?")

Starting up the Air Quality predictor...
Training the model on historical data. This might take a second...
 Found the test file at /content/Test_Features.csv. Processing now...

 Here's a look at the predictions:

     Year                            Region Predicted_Air_Quality
0    2021                       Afghanistan              Moderate
1    2022                       Afghanistan              Moderate
2    2023                       Afghanistan             Sensitive
3    2024                       Afghanistan             Sensitive
4    2021             Akrotiri and Dhekelia              Moderate
5    2022             Akrotiri and Dhekelia              Moderate
6    2023             Akrotiri and Dhekelia              Moderate
7    2024             Akrotiri and Dhekelia              Moderate
8    2021                             Aland                  Good
9    2022                             Aland                  Good
10   2023                             Aland                  Good
11   2024                             Aland                  Good
12   2021                           Albania              Moderate
13   2022                           Albania              Moderate
14   2023                           Albania              Moderate
15   2024                           Albania              Moderate
16   2021                           Algeria              Moderate
17   2022                           Algeria              Moderate
18   2023                           Algeria              Moderate
19   2024                           Algeria              Moderate
20   2021                    American Samoa                  Good
21   2022                    American Samoa                  Good
22   2023                    American Samoa                  Good
23   2024                    American Samoa                  Good
24   2021                           Andorra                  Good
25   2022                           Andorra                  Good
26   2023                           Andorra                  Good
27   2024                           Andorra                  Good
28   2021                            Angola              Moderate
29   2022                            Angola              Moderate
30   2023                            Angola              Moderate
31   2024                            Angola              Moderate
32   2021                          Anguilla                  Good
33   2022                          Anguilla                  Good
34   2023                          Anguilla                  Good
35   2024                          Anguilla                  Good
36   2021               Antigua and Barbuda                  Good
37   2022               Antigua and Barbuda                  Good
38   2023               Antigua and Barbuda                  Good
39   2024               Antigua and Barbuda                  Good
40   2021                         Argentina              Moderate
41   2022                         Argentina              Moderate
42   2023                         Argentina              Moderate
43   2024                         Argentina              Moderate
44   2021                           Armenia              Moderate
45   2022                           Armenia              Moderate
46   2023                           Armenia              Moderate
47   2024                           Armenia              Moderate
48   2021                             Aruba                  Good
49   2022                             Aruba                  Good
50   2023                             Aruba                  Good
51   2024                             Aruba                  Good
52   2021                         Australia                  Good
53   2022                         Australia                  Good
54   2023                         Australia                  Good
55   2024                         Australia                  Good
56   2021                           Austria                  Good
57   2022                           Austria                  Good
58   2023                           Austria                  Good
59   2024                           Austria                  Good
60   2021                        Azerbaijan              Moderate
61   2022                        Azerbaijan              Moderate
62   2023                        Azerbaijan              Moderate
63   2024                        Azerbaijan              Moderate
64   2021                           Bahamas                  Good
65   2022                           Bahamas                  Good
66   2023                           Bahamas                  Good
67   2024                           Bahamas                  Good
68   2021                           Bahrain              Critical
69   2022                           Bahrain              Critical
70   2023                           Bahrain             Sensitive
71   2024                           Bahrain             Sensitive
72   2021                        Bangladesh              Critical
73   2022                        Bangladesh              Critical
74   2023                        Bangladesh              Critical
75   2024                        Bangladesh              Critical
76   2021                          Barbados                  Good
77   2022                          Barbados                  Good
78   2023                          Barbados                  Good
79   2024                          Barbados                  Good
80   2021                           Belarus              Moderate
81   2022                           Belarus                  Good
82   2023                           Belarus              Moderate
83   2024                           Belarus              Moderate
84   2021                           Belgium                  Good
85   2022                           Belgium                  Good
86   2023                           Belgium                  Good
87   2024                           Belgium                  Good
88   2021                            Belize                  Good
89   2022                            Belize                  Good
90   2023                            Belize              Moderate
91   2024                            Belize              Moderate
92   2021                             Benin             Sensitive
93   2022                             Benin             Sensitive
94   2023                             Benin             Sensitive
95   2024                             Benin             Sensitive
96   2021                           Bermuda                  Good
97   2022                           Bermuda                  Good
98   2023                           Bermuda                  Good
99   2024                           Bermuda                  Good
100  2021                            Bhutan              Moderate
101  2022                            Bhutan              Moderate
102  2023                            Bhutan              Moderate
103  2024                            Bhutan              Moderate
104  2021                           Bolivia              Moderate
105  2022                           Bolivia              Moderate
106  2023                           Bolivia              Moderate
107  2024                           Bolivia             Sensitive
108  2021  Bonaire; Sint Eustatius and Saba                  Good
109  2022  Bonaire; Sint Eustatius and Saba                  Good
110  2023  Bonaire; Sint Eustatius and Saba                  Good
111  2024  Bonaire; Sint Eustatius and Saba                  Good
112  2021            Bosnia and Herzegovina              Moderate
113  2022            Bosnia and Herzegovina              Moderate
114  2023            Bosnia and Herzegovina              Moderate
115  2024            Bosnia and Herzegovina              Moderate
116  2021                          Botswana              Moderate
117  2022                          Botswana              Moderate
118  2023                          Botswana              Moderate
119  2024                          Botswana              Moderate
120  2021                            Brazil              Moderate
121  2022                            Brazil              Moderate
122  2023                            Brazil              Moderate
123  2024                            Brazil              Moderate
124  2021            British Virgin Islands                  Good
125  2022            British Virgin Islands                  Good
126  2023            British Virgin Islands                  Good
127  2024            British Virgin Islands                  Good
128  2021                            Brunei                  Good
129  2022                            Brunei                  Good
130  2023                            Brunei                  Good
131  2024                            Brunei                  Good
132  2021                          Bulgaria              Moderate
133  2022                          Bulgaria              Moderate
134  2023                          Bulgaria              Moderate
135  2024                          Bulgaria              Moderate
136  2021                      Burkina Faso              Moderate
137  2022                      Burkina Faso             Sensitive
138  2023                      Burkina Faso              Moderate
139  2024                      Burkina Faso              Moderate
140  2021                           Burundi             Sensitive
141  2022                           Burundi             Sensitive
142  2023                           Burundi              Moderate
143  2024                           Burundi             Sensitive
144  2021                          Cambodia              Moderate
145  2022                          Cambodia              Moderate
146  2023                          Cambodia              Moderate
147  2024                          Cambodia              Moderate
148  2021                          Cameroon             Sensitive
149  2022                          Cameroon             Sensitive
150  2023                          Cameroon             Sensitive
151  2024                          Cameroon             Sensitive
152  2021                            Canada                  Good
153  2022                            Canada                  Good
154  2023                            Canada                  Good
155  2024                            Canada                  Good
156  2021                        Cape Verde              Moderate
157  2022                        Cape Verde              Moderate
158  2023                        Cape Verde              Moderate
159  2024                        Cape Verde              Moderate
160  2021                       Caspian Sea              Moderate
161  2022                       Caspian Sea              Moderate
162  2023                       Caspian Sea              Moderate
163  2024                       Caspian Sea              Moderate
164  2021                    Cayman Islands              Moderate
165  2022                    Cayman Islands              Moderate
166  2023                    Cayman Islands              Moderate
167  2024                    Cayman Islands              Moderate
168  2021          Central African Republic              Moderate
169  2022          Central African Republic              Moderate
170  2023          Central African Republic              Moderate
171  2024          Central African Republic              Moderate
172  2021                              Chad             Sensitive
173  2022                              Chad              Moderate
174  2023                              Chad             Sensitive
175  2024                              Chad             Sensitive
176  2021                             Chile              Moderate
177  2022                             Chile              Moderate
178  2023                             Chile              Moderate
179  2024                             Chile              Moderate
180  2021                             China              Moderate
181  2022                             China              Moderate
182  2023                             China              Moderate
183  2024                             China              Moderate
184  2021                  Christmas Island                  Good
185  2022                  Christmas Island                  Good
186  2023                  Christmas Island                  Good
187  2024                  Christmas Island                  Good
188  2021                     Cocos Islands                  Good
189  2022                     Cocos Islands                  Good
190  2023                     Cocos Islands                  Good
191  2024                     Cocos Islands                  Good
192  2021                          Colombia              Moderate
193  2022                          Colombia              Moderate
194  2023                          Colombia              Moderate
195  2024                          Colombia              Moderate
196  2021                           Comoros                  Good
197  2022                           Comoros                  Good
198  2023                           Comoros                  Good
199  2024                           Comoros                  Good
200  2021                      Cook Islands                  Good
201  2022                      Cook Islands                  Good
202  2023                      Cook Islands                  Good
203  2024                      Cook Islands                  Good
204  2021                        Costa Rica              Moderate
205  2022                        Costa Rica              Moderate
206  2023                        Costa Rica              Moderate
207  2024                        Costa Rica              Moderate
208  2021                           Croatia              Moderate
209  2022                           Croatia              Moderate
210  2023                           Croatia              Moderate
211  2024                           Croatia              Moderate
212  2021                              Cuba                  Good
213  2022                              Cuba                  Good
214  2023                              Cuba                  Good
215  2024                              Cuba                  Good
216  2021                           Curaçao                  Good
217  2022                           Curaçao                  Good
218  2023                           Curaçao                  Good
219  2024                           Curaçao                  Good
220  2021                            Cyprus              Moderate
221  2022                            Cyprus              Moderate
222  2023                            Cyprus              Moderate
223  2024                            Cyprus              Moderate
224  2021                    Czech Republic              Moderate
225  2022                    Czech Republic              Moderate
226  2023                    Czech Republic              Moderate
227  2024                    Czech Republic                  Good
228  2021                     Côte d'Ivoire              Moderate
229  2022                     Côte d'Ivoire              Moderate
230  2023                     Côte d'Ivoire              Moderate
231  2024                     Côte d'Ivoire              Moderate
232  2021  Democratic Republic of the Congo             Sensitive
233  2022  Democratic Republic of the Congo             Sensitive
234  2023  Democratic Republic of the Congo              Moderate
235  2024  Democratic Republic of the Congo             Sensitive
236  2021                           Denmark                  Good
237  2022                           Denmark                  Good
238  2023                           Denmark                  Good
239  2024                           Denmark                  Good
240  2021                          Djibouti              Moderate
241  2022                          Djibouti              Moderate
242  2023                          Djibouti              Moderate
243  2024                          Djibouti              Moderate
244  2021                          Dominica                  Good
245  2022                          Dominica                  Good
246  2023                          Dominica                  Good
247  2024                          Dominica                  Good
248  2021                Dominican Republic                  Good
249  2022                Dominican Republic                  Good
250  2023                Dominican Republic                  Good
251  2024                Dominican Republic              Moderate
252  2021                           Ecuador              Moderate
253  2022                           Ecuador              Moderate
254  2023                           Ecuador              Moderate
255  2024                           Ecuador              Moderate
256  2021                             Egypt             Sensitive
257  2022                             Egypt             Sensitive
258  2023                             Egypt             Sensitive
259  2024                             Egypt             Sensitive
260  2021                       El Salvador              Moderate
261  2022                       El Salvador              Moderate
262  2023                       El Salvador              Moderate
263  2024                       El Salvador              Moderate
264  2021                 Equatorial Guinea              Moderate
265  2022                 Equatorial Guinea              Moderate
266  2023                 Equatorial Guinea              Moderate
267  2024                 Equatorial Guinea             Sensitive
268  2021                           Eritrea              Moderate
269  2022                           Eritrea              Moderate
270  2023                           Eritrea              Moderate
271  2024                           Eritrea              Moderate
272  2021                           Estonia                  Good
273  2022                           Estonia                  Good
274  2023                           Estonia                  Good
275  2024                           Estonia                  Good
276  2021                          Ethiopia              Moderate
277  2022                          Ethiopia              Moderate
278  2023                          Ethiopia              Moderate
279  2024                          Ethiopia              Moderate
280  2021                  Falkland Islands                  Good
281  2022                  Falkland Islands                  Good
282  2023                  Falkland Islands                  Good
283  2024                  Falkland Islands                  Good
284  2021                     Faroe Islands                  Good
285  2022                     Faroe Islands                  Good
286  2023                     Faroe Islands                  Good
287  2024                     Faroe Islands                  Good
288  2021                              Fiji                  Good
289  2022                              Fiji                  Good
290  2023                              Fiji                  Good
291  2024                              Fiji                  Good
292  2021                           Finland                  Good
293  2022                           Finland                  Good
294  2023                           Finland                  Good
295  2024                           Finland                  Good
296  2021                            France                  Good
297  2022                            France                  Good
298  2023                            France                  Good
299  2024                            France                  Good
300  2021                     French Guiana              Moderate
301  2022                     French Guiana              Moderate

 Success! Your classified predictions are saved to: /content/Final_Classified_Predictions.csv

In [ ]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import accuracy_score, mean_absolute_error, r2_score
import os

print("Step 1: Quickly training the model...")
features = ['Year', 'Geographic-Mean PM2.5 [ug/m3]', 'Population Coverage [%]',
            'Geographic Coverage [%]', 'pm_lag_1', 'pm_lag_2', 'pm_lag_3', 'pm_roll_3']

model = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(ts_df[features], ts_df['Target_PM25_Current_Year'])

print(" Step 2: Loading test data and making predictions...")
test_df = pd.read_csv('/content/Test_Features.csv')

test_df = test_df.rename(columns={'pm_lag1': 'pm_lag_1', 'pm_lag2': 'pm_lag_2',
                                  'pm_lag3': 'pm_lag_3', 'pm_roll3': 'pm_roll_3'})

test_df = test_df.sort_values(by=['Region', 'Year']).reset_index(drop=True)

test_df['Predicted_PM25_Number'] = model.predict(test_df[features])

print(" Step 3: Reverse-engineering the true answers from the future...")

test_df['True_PM25_Number'] = test_df.groupby('Region')['pm_lag_1'].shift(-1)

eval_df = test_df.dropna(subset=['True_PM25_Number']).copy()

print(" Step 4: Translating numbers to EPA categories and grading the test...")

def categorize_pm25(val):
    if val <= 12.0: return 'Good'
    elif val <= 35.4: return 'Moderate'
    elif val <= 55.4: return 'Sensitive'
    else: return 'Critical'

eval_df['Predicted_Class'] = eval_df['Predicted_PM25_Number'].apply(categorize_pm25)
eval_df['True_Class'] = eval_df['True_PM25_Number'].apply(categorize_pm25)

class_accuracy = accuracy_score(eval_df['True_Class'], eval_df['Predicted_Class'])
r2 = r2_score(eval_df['True_PM25_Number'], eval_df['Predicted_PM25_Number'])
mae = mean_absolute_error(eval_df['True_PM25_Number'], eval_df['Predicted_PM25_Number'])

print("\n" + "=" * 45)
print(" FINAL REPORT CARD (TEST DATA EVALUATION)")
print("=" * 45)
print(f"Category Accuracy:  {class_accuracy * 100:.2f}% (How often did we guess the right text label?)")
print(f"Numeric Accuracy:   {r2 * 100:.2f}% (How close were our raw numbers?)")
print(f"Average Error:      Off by {mae:.2f} ug/m3 on average")
print("=" * 45)

Step 1: Quickly training the model...
 Step 2: Loading test data and making predictions...
 Step 3: Reverse-engineering the true answers from the future...
 Step 4: Translating numbers to EPA categories and grading the test...

=============================================
 FINAL REPORT CARD (TEST DATA EVALUATION)
=============================================
Category Accuracy:  96.75% (How often did we guess the right text label?)
Numeric Accuracy:   98.69% (How close were our raw numbers?)
Average Error:      Off by 0.95 ug/m3 on average
=============================================

In [ ]:
import joblib
from google.colab import files

print("Time to pack everything up and ship it to your computer...")

model_filename = 'pm25_random_forest_model.pkl'
joblib.dump(model, model_filename)
print(f"  ✓ Success! Your trained model is safely packaged as '{model_filename}'")

report_filename = 'Model_Accuracy_Report.txt'

with open(report_filename, 'w') as f:
    f.write(" PM2.5 MODEL EVALUATION REPORT 📊\n")
    f.write("=" * 45 + "\n")
    f.write(f"Category Accuracy:  {class_accuracy * 100:.2f}%\n")
    f.write(f"Numeric Accuracy:   {r2 * 100:.2f}%\n")
    f.write(f"Average Error:      {mae:.2f} ug/m3\n")
    f.write("=" * 45 + "\n")
    f.write("Note: Accuracy was calculated using the 'future-lag' reverse-engineering trick.\n")

print(f"  ✓ Success! Report card saved as '{report_filename}'")

print("\n Initiating downloads... (Keep an eye on your browser's download queue!)")
print("Note: If your browser asks for permission to download multiple files, make sure to click 'Allow'.")


files.download(model_filename)

files.download(report_filename)

files.download('/content/Final_Classified_Predictions_with_Accuracy.csv')

Time to pack everything up and ship it to your computer...
  ✓ Success! Your trained model is safely packaged as 'pm25_random_forest_model.pkl'
  ✓ Success! Report card saved as 'Model_Accuracy_Report.txt'

 Initiating downloads... (Keep an eye on your browser's download queue!)
Note: If your browser asks for permission to download multiple files, make sure to click 'Allow'.

FileNotFoundError: Cannot find file: /content/Final_Classified_Predictions_with_Accuracy.csv